### PR TITLE
Add Typings

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by yocontra** [comment]
Aren't these usually kept in another module?

**Comment by tusharmath** [comment]
I can't answer if its "usual" but putting it inside the same npm package definitely will make the project much easier to integrate with, while using typescript. Secondly its easier to maintain because you only have one repo.

**Comment by yocontra** [comment]
From what I understand most people keep it in another module, and keep that versioned with the parent module. I don't work with typescript so I can't commit to maintaining the typing file if changes happen, but I'll merge this for now.

**Comment by tusharmath** [comment]
@contra You could give me a buzz if you'd like me to update the typings anytime.

Has the new version been published to npm?

**Pull request merged**
